import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ContextProiver } from "@/lib/loading_hook";
import {Toaster} from "react-hot-toast"
import ConnectSocket from "@/components/connect-socket";
import Script from "next/script";
import { Sidebar } from "@/components/sidebar";
import { Axios } from "@/lib/axiosInstance";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

    
   
  return (
    <html lang="en">
      <Script
   src="https://kit.fontawesome.com/ecb364a250.js"
   crossOrigin="anonymous"
 />
      <body
        className={`${geistSans.variable}  ${geistMono.variable} h-dvh bg-[#111111]  w-full  antialiased`}
      >
        <ContextProiver >
      <Toaster />
      <ConnectSocket />
      <div className="flex h-full">

        {children}
      </div>
        </ContextProiver>
      </body>
    </html>
  );
}
